import { useSignals, useBotStatus, useBotControl, useTrades, usePortfolio } from "@/hooks/use-dashboard";
import { StatCard } from "@/components/dashboard/StatCard";
import { SignalCard } from "@/components/dashboard/SignalCard";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Activity, PlayCircle, StopCircle, Wallet, TrendingUp, Cpu } from "lucide-react";
import { cn } from "@/lib/utils";

// Mock data for chart until we have real history endpoint
const chartData = [
  { time: "00:00", value: 42000 },
  { time: "04:00", value: 42500 },
  { time: "08:00", value: 41800 },
  { time: "12:00", value: 43200 },
  { time: "16:00", value: 43800 },
  { time: "20:00", value: 44100 },
  { time: "24:00", value: 43900 },
];

export default function Dashboard() {
  const { data: signals } = useSignals();
  const { data: trades } = useTrades();
  const { data: botStatus } = useBotStatus();
  const { mutate: controlBot, isPending: isControlling } = useBotControl();
  const { data: portfolio } = usePortfolio();

  const totalBalance = portfolio?.reduce((acc, item) => acc + item.total * 1, 0) || 0; // Simplified
  const activeSignals = signals?.filter(s => s.status === 'active') || [];
  
  return (
    <div className="p-4 md:p-8 space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-display font-bold text-gradient">Dashboard</h1>
          <p className="text-muted-foreground mt-1">Real-time market analysis and bot performance.</p>
        </div>
        
        <div className="flex items-center gap-3">
          <div className={cn(
            "flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium border",
            botStatus?.isRunning 
              ? "bg-green-500/10 text-green-500 border-green-500/20" 
              : "bg-red-500/10 text-red-500 border-red-500/20"
          )}>
            <div className={cn("w-2 h-2 rounded-full animate-pulse", botStatus?.isRunning ? "bg-green-500" : "bg-red-500")} />
            {botStatus?.isRunning ? "System Active" : "System Paused"}
          </div>
          
          <button
            onClick={() => controlBot(botStatus?.isRunning ? "stop" : "start")}
            disabled={isControlling}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-lg font-semibold transition-all duration-200",
              botStatus?.isRunning
                ? "bg-red-500/10 text-red-500 hover:bg-red-500/20 active:scale-95"
                : "bg-primary text-primary-foreground hover:bg-primary/90 active:scale-95"
            )}
          >
            {isControlling ? (
              <Cpu className="w-4 h-4 animate-spin" />
            ) : botStatus?.isRunning ? (
              <StopCircle className="w-4 h-4" />
            ) : (
              <PlayCircle className="w-4 h-4" />
            )}
            {botStatus?.isRunning ? "Stop Engine" : "Start Engine"}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard
          title="Total Balance"
          value={`$${totalBalance.toLocaleString()}`}
          trend={{ value: 12.5, isPositive: true }}
          icon={<Wallet className="h-6 w-6" />}
          subtitle="Estimated value"
        />
        <StatCard
          title="Active Signals"
          value={activeSignals.length}
          trend={{ value: 2, isPositive: true }}
          icon={<Activity className="h-6 w-6" />}
          subtitle="Generated by AI"
        />
        <StatCard
          title="24h Profit"
          value="+$124.50"
          trend={{ value: 4.2, isPositive: true }}
          icon={<TrendingUp className="h-6 w-6" />}
          subtitle="Last 24 hours"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[500px]">
        {/* Chart Section */}
        <div className="lg:col-span-2 rounded-2xl border border-white/5 bg-card/50 p-6 backdrop-blur-xl">
          <div className="mb-6 flex items-center justify-between">
            <h3 className="font-semibold text-lg">Market Trend</h3>
            <select className="bg-white/5 border border-white/10 rounded-lg px-2 py-1 text-sm text-muted-foreground outline-none">
              <option>BTC/USDT</option>
              <option>ETH/USDT</option>
            </select>
          </div>
          <div className="h-[400px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10B981" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#10B981" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="time" stroke="#6b7280" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#6b7280" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#1f2937', border: 'none', borderRadius: '8px' }}
                  itemStyle={{ color: '#fff' }}
                />
                <Area type="monotone" dataKey="value" stroke="#10B981" strokeWidth={2} fillOpacity={1} fill="url(#colorValue)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Signals Feed */}
        <div className="flex flex-col gap-4 rounded-2xl border border-white/5 bg-card/50 p-6 backdrop-blur-xl overflow-hidden">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-lg flex items-center gap-2">
              <Cpu className="h-5 w-5 text-accent" />
              Live Signals
            </h3>
            <span className="text-xs text-muted-foreground bg-white/5 px-2 py-1 rounded-full">
              {activeSignals.length} Active
            </span>
          </div>
          
          <div className="flex-1 overflow-y-auto space-y-3 pr-2 scrollbar-thin scrollbar-thumb-white/10 hover:scrollbar-thumb-white/20">
            {activeSignals.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground text-sm opacity-60">
                <Activity className="h-8 w-8 mb-2" />
                <p>No active signals</p>
                <p className="text-xs">Waiting for market opportunities...</p>
              </div>
            ) : (
              activeSignals.map((signal) => (
                <SignalCard key={signal.id} signal={signal} />
              ))
            )}
          </div>
        </div>
      </div>

      {/* Recent Trades Table */}
      <div className="rounded-2xl border border-white/5 bg-card/50 p-6 backdrop-blur-xl">
        <h3 className="font-semibold text-lg mb-4">Recent Executions</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-muted-foreground uppercase text-xs border-b border-white/5">
              <tr>
                <th className="px-4 py-3 font-medium">Time</th>
                <th className="px-4 py-3 font-medium">Symbol</th>
                <th className="px-4 py-3 font-medium">Side</th>
                <th className="px-4 py-3 font-medium text-right">Price</th>
                <th className="px-4 py-3 font-medium text-right">Amount</th>
                <th className="px-4 py-3 font-medium text-right">PnL</th>
                <th className="px-4 py-3 font-medium text-center">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {trades?.map((trade) => (
                <tr key={trade.id} className="hover:bg-white/5 transition-colors">
                  <td className="px-4 py-3 font-mono text-muted-foreground">
                    {trade.timestamp && new Date(trade.timestamp).toLocaleTimeString()}
                  </td>
                  <td className="px-4 py-3 font-medium">{trade.symbol}</td>
                  <td className="px-4 py-3">
                    <span className={cn(
                      "px-2 py-0.5 rounded text-xs font-semibold uppercase",
                      trade.side === 'buy' ? "text-green-500 bg-green-500/10" : "text-red-500 bg-red-500/10"
                    )}>
                      {trade.side}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right font-mono">${trade.price}</td>
                  <td className="px-4 py-3 text-right font-mono">{trade.amount}</td>
                  <td className={cn("px-4 py-3 text-right font-mono", 
                    trade.pnl && !trade.pnl.startsWith('-') ? "text-green-500" : "text-red-500"
                  )}>
                    {trade.pnl || '-'}
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={cn(
                      "inline-block w-2 h-2 rounded-full",
                      trade.status === 'open' ? "bg-blue-500" : "bg-gray-500"
                    )} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {!trades?.length && (
            <p className="text-center text-muted-foreground py-8">No trades recorded yet.</p>
          )}
        </div>
      </div>
    </div>
  );
}
